### ISSUE TITLE
Popup menu of the browser is still showing on Ubuntu

### ISSUE THREAD

**Issue by ibobak** [EliotVU/Addon-Image-Resizer#24]
I have Ubuntu 20.04, latest Firefox.  If I am pressing right mouse button and dragging right bottom (to increase) - it increases fine, but it also shows the popup menu of the browser in the point where I clicked.

Question: how to avoid showing this popup menu?

**Comment by EliotVU** [comment]
You may want to try and set dom.event.contextmenu.enabled to false, type about:config in your URL bar and search for dom.event.contextmenu.enabled, double click it to toggle, the value should read true. 

This enables the addon to block the context menu from popping up, unfortunately downside to this is that websites may also block or overwrite the contextmenu's behavior, which may be undesirable(you can hold shift to override this behavior).
